:: this is generated by LLM and I haven't tested it.
@echo off
setlocal enabledelayedexpansion

:: Determine architecture
for /f %%i in ('wmic os get osarchitecture') do set ARCH=%%i

:: Set Raylib version
set RAYLIB_VERSION=5.0

:: Set URL based on architecture
if "%ARCH%"=="64-bit" (
    set RAYLIB_URL=https://github.com/raysan5/raylib/releases/download/%RAYLIB_VERSION%/raylib-%RAYLIB_VERSION%_win64_mingw-w64.zip
    set RAYLIB_FOLDER=raylib-%RAYLIB_VERSION%_win64_mingw-w64
) else (
    set RAYLIB_URL=https://github.com/raysan5/raylib/releases/download/%RAYLIB_VERSION%/raylib-%RAYLIB_VERSION%_win32_mingw-w64.zip
    set RAYLIB_FOLDER=raylib-%RAYLIB_VERSION%_win32_mingw-w64
)

:: Download raylib if not already present
if not exist "%RAYLIB_FOLDER%" (
    echo Downloading raylib...
    curl -L -o raylib.zip %RAYLIB_URL%
    tar -xf raylib.zip
    del raylib.zip
)

:: Set paths
set INCLUDE_PATH_RAYLIB=%cd%\%RAYLIB_FOLDER%\include\
set INCLUDE_PATH=%cd%\src\include\
set LIB_PATH=%cd%\%RAYLIB_FOLDER%\lib\

:: Create bin directory if not exists
if not exist bin mkdir bin

:: Compile the project
gcc ".\src\fractal.c" ".\src\world.c" -o .\bin\fractal.exe -I%INCLUDE_PATH_RAYLIB% -I%INCLUDE_PATH% -L%LIB_PATH% -l:libraylib.a -lm

echo Compilation completed.
pause
